/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>

#include "stm32f1xx.h"     // Device header

/*
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
*/


int main(void)
{
	RCC->APB2ENR = 0x0204; //konfigurasi clock ADC1 dan GPIOA
	GPIOA-> CRL = 0x0003; //PA1=0 konfigurasi pin GPIOA1 sebagai input
	RCC-> CFGR = 0x8000; //bit15:14
	ADC1-> SMPR2 = 0x0038; //set channel 1 max sampling rate
	ADC1-> SQR3 = 0x0001; //select channel 1
	ADC1-> CR2 = 0x0003; //enable ADC First time
	ADC1-> CR2 = 0x0003; //enable ADC Second time
	ADC1-> CR2 = 0x0007; //ON calibration

    /* Loop forever */
	while (1){
		ADC1->CR2|=0x400000;
		while (!(ADC1->SR &2)){}
		int analogVal=ADC1->DR;
		printf("Analog Value is %d", analogVal);
		printf("/r/n");
	}
}
